# Basic
title: ç‹æµ©
subtitle: å®ƒå«è‡³å°Šå®
description: æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººç«™~
# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: webå·¥ç¨‹å¸ˆ
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc:  æ‹’ç»æµ®èº
url: "wanghao.github.io"

# Comment
comment:
    # disqus: leopard
    duoshuo: leopard 
    uyan: 384626608

# Social
social:
    weibo: 384626608
    github: wanghaoweb
    # twitter: 
    mail: 18330116437@163.com

# ç™¾åº¦ç»Ÿè®¡ 
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id 
baidu:
    id:

# Google Analytics
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
ga:
    id:
    host: auto  


# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹
#
#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}   
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}      
    - {title: å…³äºæˆ‘, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


